### ISSUE TITLE
项目运行不起来，能否提供一下两个端通信示列？

### ISSUE THREAD

**Issue by mxdlsm** [NicoLiutong/SocketClient#1]

**Comment by NicoLiutong** [comment]
你的网络权限有没有打开

**Comment by mxdlsm** [comment]
这里什么都没有
<img width="688" alt="CleanShot 2023-08-15 at 15 48 37@2x" src="https://github.com/NicoLiutong/SocketClient/assets/22886455/cf520015-e704-482a-af5e-c59dcc8996bd">

**Comment by NicoLiutong** [comment]
你需要在你自己项目的AndroidManifest里边添加

**Comment by mxdlsm** [comment]
好的，谢谢。那另一台设备（相当于服务端）怎么写呀？

**Comment by NicoLiutong** [comment]
服务器的暂时没有开发
